### ISSUE TITLE
Gunma prefecture related providers

### ISSUE THREAD

**Issue by szjozsef** [tshimada291/gtfs-jp-list-datecheck#1]
The Gunma prefecture does not publish anymore the GTFS files to the https://gma.jcld.jp/GMA_OPENDATA/GTFS/... cloud website, instead every provider publish their feeds directly or via one of the centrally managed GTFS Opendata providers: (ex: https://gtfs-data.jp/, https://ckan.odpt.org/)
Please see some uupdated info here: [https://github.com/transitland/transitland-atlas/pull/880](https://github.com/transitland/transitland-atlas/pull/880)
Source: https://www.pref.gunma.jp/page/198829.html

**Comment by tshimada291** [comment]
Dear szjosef:
Thank you for your kindness. However, I know what Gunma GTFS Web site is already closed in April, and all related links have already been removed from my list.

I hope Transitland will update their list or database.

* Please know that this is a unofficially list and cannot be updated immediately.

Best Regards.

**Comment by drewda** [comment]
Hello, @tshimada291. Thank you for creating a great resource for finding Japanese GTFS feeds.

To convert your list into the Transitland Atlas DMFR format, we were relying on your `fixed_current_basename` column. I see that column is no longer in `GTFS_fixedURL.csv`. Would you consider adding that column again?

Or if that is not possible, we'll need to look into other ways to revise our script at https://github.com/transitland/transitland-atlas/blob/master/scripts/convert-jp-list-csv-to-dmfr.py

Thank you
